aws/codecatalyst-blueprints

- .github/workflows/secret-scan-action.yml
> fix: secret scanning

- packages/blueprints/sam-serverless-app/README.md
- packages/blueprints/sam-serverless-app/src/__snapshots__/blueprint-snapshot-driver.spec.ts.snap
- packages/blueprints/sam-serverless-app/src/readmeContents.ts
N/A
Update SAM blueprint architecture diagram link
---
> fix(blueprint): update SAM blueprint architecture diagram link

- packages/blueprints/gen-ai-chatbot/README.md
> chore(chatbot): update readme

- packages/blueprints/gen-ai-chatbot/README.md
> chore(chatbot): add disclaimer and license information

- packages/blueprints/gen-ai-chatbot/.projenrc.ts
- packages/blueprints/gen-ai-chatbot/package.json
> fix: author naming for the Gen AI blueprint

- packages/blueprints/gen-ai-chatbot/README.md
- packages/blueprints/gen-ai-chatbot/src/blueprint.ts
- packages/blueprints/gen-ai-chatbot/src/workflows.ts
#501 
```
commit 4d75e94e2da9f8354974f81cc1437e308f23f92e (HEAD -> chore/compute, origin/chore/compute)
Author: Steve Keppeler <keppeler@amazon.com>
Date:   Tue Mar 12 14:58:48 2024 -0400
chore: update documentation on role and model access
* update documentation to specify the developer role may be used
* add an issue as a hint to the user to validate models are accessible
commit dfbece5c086c02f86d62b8d712153614759b5939
Author: Steve Keppeler <keppeler@amazon.com>
Date:   Tue Mar 12 14:43:06 2024 -0400
chore: increase disk space for CDK deploy
```
---
> compute & readme updates

- packages/blueprints/gen-ai-chatbot/src/blueprint.ts
- packages/blueprints/gen-ai-chatbot/src/workflows.ts
#501
Revert previous commit to increase disk space as that compute instance is not available in the free tier.
---
> Revert "chore: increase disk space for CDK deploy"

- packages/blueprints/gen-ai-chatbot/src/blueprint.ts
- packages/blueprints/gen-ai-chatbot/src/workflows.ts
- packages/components/workflows/src/actions/action-build.ts
- packages/components/workflows/src/actions/action-cfn-cleanup.ts
```
commit f265200195f197f58e7d29c5a2ea6ada546ab276 (HEAD -> chore/validate-access, origin/chore/validate-access)
Author: Steve Keppeler <keppeler@amazon.com>
Date:   Fri Mar 15 14:59:18 2024 -0400
fix(chatbot): add null check on distributions
commit 6db838194fdeb0ab2e10ffc56fe1246437bb6fb0
Author: Steve Keppeler <keppeler@amazon.com>
Date:   Fri Mar 15 14:58:48 2024 -0400
chore(chatbot): add cognito pool cleanup script
commit 5713bcd82701eba46b1c7752ad563b987123e714
Author: Steve Keppeler <keppeler@amazon.com>
Date:   Fri Mar 15 14:58:27 2024 -0400
chore(chatbot): validate model access in workflow
* add workflow step to validate the account has access to Bedrock in the defined region
* add additional documentation to configuration
```
Add any other context …
> validate model access (and cognito cleanup)

- packages/components/source-repositories/src/static-assets.ts
> fix(source-repositories): fix static asset pathing

- packages/blueprints/gen-ai-chatbot/src/blueprint.ts
- packages/components/workflows/src/actions/action-cfn-cleanup.ts
* add script to delete IP sets associated with the WAF stack
* only attempt to delete web ACL if it exists
---
> chore(chatbot): add IP set cleanup script

- packages/components/source-repositories/src/static-assets.ts
> fix: handle potentially null glob

- packages/blueprints/launch-blueprint/src/inline-policy-deploy.json
- packages/blueprints/launch-blueprint/src/trust-policy.json
> fix(launch): add missing inline policies

- packages/blueprints/gen-ai-chatbot/src/workflows.ts
- packages/components/workflows/src/actions/action-cdk-bootstrap.ts
- packages/components/workflows/src/actions/action-cdk-deploy.ts
Allow the author to configure the CDK version to be used with the CDK action.
---
> chore: allow configuration of CDK version

- packages/blueprints/gen-ai-chatbot/src/workflows.ts
- packages/components/workflows/src/actions/action-build.ts
* use curated image in chatbot workflow and remove usage of custom image since the curated one now includes node 18
---
> chore: add codecalyst curated image

- packages/blueprints/launch-blueprint/src/blueprint.ts
> feat: add source branch option

- packages/blueprints/launch-blueprint/src/blueprint.ts
> fix(launch): correct glob path

- packages/blueprints/launch-blueprint/.projenrc.ts
- packages/blueprints/launch-blueprint/package.json
> fix: allow launch options to be changed

- packages/components/workflows/src/actions/action.ts
> chore: add github action runner override identifier

- packages/blueprints/launch-blueprint/package.json
- packages/blueprints/launch-blueprint/src/blueprint.ts
- packages/blueprints/launch-blueprint/src/defaults.json
Adds Dynamic KV parameters to the launch blueprint.  Deprecates the existing simple tuple options.
Local synthesis using modified options.  Verification of workflow mappings.
N/A
---
> feat(launch): add dynamic KV to launch blueprint

- packages/blueprints/launch-blueprint/src/blueprint.ts
Filter workflow files that are applicable for mapping transformations in the launch blueprint.
Local synthesis using a repository with non-yaml and yaml files in the workflows directory.
N/A
---
> feat(launch): filter workflow transformations

- packages/blueprints/launch-blueprint/src/blueprint.ts
Launch blueprint to support action groups.
Local invocation against workflow with root and and nested actions.
N/A
---
> feat(launch): map launch parameters to action groups

- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-components/backend/python/app/usecases/bot.py
> fix(chatbot): correct embedding import

- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-components/frontend/package.json
> fix(chatbot): add missing frontend import

- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai/README.md
* remove information from readme that does not pertain to CodeCatalyst
---
> chore(chatbot): remove irrelevant information from readme

- packages/blueprints/blueprint-builder/src/blueprint.ts
> fix: bug in how merge strategies are applied

- packages/components/environments/src/environment-component.ts
> fix(environment-component): default name field if none is provided in the component

- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-components/frontend/.env.template
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-components/frontend/src/hooks/useScroll.ts
- packages/blueprints/gen-ai-chatbot/static-assets/docs/LOCAL_DEVELOPMENT.md
Change scroll behavior to instant for scroll to bottom. This fixes the fast jitter when text is being generated and you are near the bottom of the page.
Also updated the readme and .env.template file to make it easier to understand how to develop the front end locally.
Manually tested
Requested fix for Alex Forsyth's demo.
---
> fix: scroll jitter

- packages/blueprints/blueprint-builder/static-assets/release.sh
https://t.corp.amazon.com/V1400549710/communication
---
> disable projen in blueprint-builder release.sh

- packages/utils/blueprint-cli/src/index.ts
- packages/utils/blueprint-cli/src/publish/publish.ts
- packages/utils/blueprint-cli/src/publish/set-catalog-version.ts
We need to allow people to upgrade the catalog from the CLI
---
> feat: allow --update-catalog flag

- packages/blueprints/gen-ai-chatbot/src/blueprint.ts
- packages/blueprints/gen-ai-chatbot/src/workflows.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/api.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/auth.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/embedding.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/frontend.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/usage-analysis.ts
- packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-cdk/lib/constructs/websocket.ts
* update cdk structure to nest all CDK related files under the cdk/ directory
* this aligns the blueprint with the application's source repository
---
> chore(chatbot): update cdk structure

- packages/blueprints/blueprint-builder/src/build-release-workflow.ts
Adding workflow build action container image for solving this sev2: https://t.corp.amazon.com/P139371813/communication
published to personal space and ran the release workflow successfully
> fix: builder blueprint workflow build aciton image issue
